version: '3.8'
services:

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=changeme        # Пароль для elastic (для демо)
      - "discovery.type=single-node"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.verification_mode=full"
      - "xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elastic.key"
      - "xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elastic.crt"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./certs:/usr/share/elasticsearch/config/certs
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk
    restart: always

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - "xpack.security.encryptionKey=abcd1234"
      - "elasticsearch.ssl.verificationMode=full"
      - "elasticsearch.ssl.certificateAuthorities=/usr/share/kibana/config/certs/ca.crt"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTNAME=elastic/kibana
      - ELASTICSEARCH_SECURITY_SERVICETOKENS_TOKEN_KIBANA=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYV90b2tlbjpqa2ZUOGZmSlNXcTl3Z240dkw5d2tR

    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    environment:
      - "xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200"
      - "xpack.monitoring.elasticsearch.username=elastic"
      - "xpack.monitoring.elasticsearch.password=changeme"
      - "xpack.monitoring.elasticsearch.ssl.ca_truststore.path=/usr/share/logstash/config/certs/ca.crt"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5044:5044"  # TLS порт для Filebeat
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    entrypoint: >
      sh -c "sleep 5 && filebeat -e -c /usr/share/filebeat/filebeat.yml"  # Добавлено sleep 5 для ожидания сертификатов
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log:/var/log:ro
      - ./certs:/usr/share/filebeat/certs
      - filebeat_data:/usr/share/filebeat/data
    networks:
      - elk
    depends_on:
      - logstash
    restart: always

volumes:
  elasticsearch_data:
  filebeat_data:

networks:
  elk:
    driver: bridge